config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),
    path('users/', include('users.urls')),
    path('mailing/', include('mailing.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mailing.apps import MailingConfig
from mailing.views import CustomerListView, CustomerUpdateView, CustomerDeleteView, \
    CustomerCreateView, MailingSettingsListView, MailingSettingsCreateView, MailingSettingsUpdateView, \
    MailingSettingsDeleteView, MailingClientsListView, toggle_customer, MessageListView, MessageUpdateView, \
    MessageDeleteView, MessageCreateView, HomePageView

app_name = MailingConfig.name

urlpatterns = [
    path('customers/', CustomerListView.as_view(), name='customers'),
    path('customers/update/<int:pk>', CustomerUpdateView.as_view(), name='customer_update'),
    path('customers/delete/<int:pk>', CustomerDeleteView.as_view(), name='customer_delete'),
    path('customers/create/', CustomerCreateView.as_view(), name='customer_create'),

    path('', MailingSettingsListView.as_view(), name='mailing_list'),
    path('create/', MailingSettingsCreateView.as_view(), name='mailing_create'),
    path('update/<int:pk>/', MailingSettingsUpdateView.as_view(), name='mailing_update'),
    path('delete/<int:pk>/', MailingSettingsDeleteView.as_view(), name='mailing_delete'),

    path('<int:pk>/clients/', MailingClientsListView.as_view(), name='mailing_clients'),
    path('<int:pk>/clients/add/<int:customer_pk>', toggle_customer, name='mailing_clients_toggle'),

    path('messages/', MessageListView.as_view(), name='messages'),
    path('messages/update/<int:pk>', MessageUpdateView.as_view(), name='message_update'),
    path('messages/delete/<int:pk>', MessageDeleteView.as_view(), name='message_delete'),
    path('messages/create/', MessageCreateView.as_view(), name='message_create'),

    path('homepage/', cache_page(60)(HomePageView.as_view()), name='mailing_homepage')
]

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, ActivateView, CustomPasswordResetView, \
    CustomPasswordResetDoneView, CustomPasswordResetConfirmView, CustomPasswordResetCompleteView, UserUpdateView, \
    generate_new_password

app_name = UsersConfig.name
urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('register/', RegisterView.as_view(), name='register'),
    path('activate/<uidb64>/<token>', ActivateView.as_view(), name='activate'),

    path('reset_password/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('reset_password_sent/', CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset_password_complete/', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('genpassword/', generate_new_password, name='generate_new_password'),


    path('profile/', UserUpdateView.as_view(), name='profile')
]

mailing/models.py
from django.conf import settings
from django.db import models

from catalog.models import NULLABLE


class Customer(models.Model):
    email = models.EmailField(unique=True, verbose_name='Email')
    first_name = models.CharField(max_length=150, **NULLABLE, verbose_name='Имя')
    last_name = models.CharField(max_length=150, **NULLABLE, verbose_name='Фамилия')
    comment = models.TextField(**NULLABLE, verbose_name='Комментарий')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, **NULLABLE, verbose_name='Пользователь')

    def __str__(self):
        return f'{self.first_name} {self.last_name} - {self.email}'

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'


class Message(models.Model):
    subject = models.CharField(max_length=250, verbose_name='Тема письма')
    body = models.TextField(verbose_name='Тело письма')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, **NULLABLE,
                              verbose_name='Пользователь')

    def __str__(self):
        return self.subject

    class Meta:
        verbose_name = 'Письмо'
        verbose_name_plural = 'Письма'


class MailingSettings(models.Model):
    PERIOD_DAILY = 'daily'
    PERIOD_WEEKLY = 'weekly'
    PERIOD_MONTHLY = 'monthly'

    PERIODS = (
        (PERIOD_DAILY, 'Ежедневная'),
        (PERIOD_WEEKLY, 'Раз в неделю'),
        (PERIOD_MONTHLY, 'Раз в месяц')

    )

    STATUS_CREATED = 'created'
    STATUS_STARTED = 'started'
    STATUS_DONE = 'done'

    STATUSES = (
        (STATUS_STARTED, 'Запущена'),
        (STATUS_CREATED, 'Создана'),
        (STATUS_DONE, 'Завершена')
    )

    start_time = models.DateTimeField(verbose_name='Время старта')
    end_time = models.DateTimeField(verbose_name='Время окончания')
    period = models.CharField(max_length=20, choices=PERIODS, verbose_name='Периодичность')
    status = models.CharField(max_length=20, choices=STATUSES, verbose_name='Статус рассылки')

    message = models.ForeignKey(Message, on_delete=models.CASCADE, verbose_name='Сообщение')

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, **NULLABLE,
                              verbose_name='Пользователь')
    def __str__(self):
        return f"{self.start_time} - {self.period}"

    class Meta:
        verbose_name = 'Paccылка'
        verbose_name_plural = 'Рассылки'
        ordering = ('start_time',)

        # кастомное право доступа на отключение рассылок
        permissions = [
            ('set_status', 'Can change status')
        ]


class MailingClient(models.Model):
    client = models.ForeignKey(Customer, on_delete=models.CASCADE, verbose_name='Клиент')
    settings = models.ForeignKey(MailingSettings, on_delete=models.CASCADE, verbose_name='Настройки')

    def __str__(self):
        return f'{self.client} - {self.settings}'

    class Meta:
        verbose_name = 'Клиент рассылки'
        verbose_name_plural = 'Клиенты рассылки'


class MailingLog(models.Model):
    STATUS_OK = 'ok'
    STATUS_FAILED = 'failed'
    STATUSES = (
        (STATUS_OK, 'Успешно'),
        (STATUS_FAILED, 'Ошибка')
    )

    last_try = models.DateTimeField(auto_now_add=True, verbose_name='Дата и время последней попытки')
    client = models.ForeignKey(Customer, on_delete=models.CASCADE, verbose_name='Клиент')
    settings = models.ForeignKey(MailingSettings, on_delete=models.CASCADE, verbose_name='Настройки')
    status = models.CharField(max_length=20, choices=STATUSES, default=STATUS_OK, verbose_name='Статус')
    server_response = models.TextField(**NULLABLE, verbose_name='Ответ сервера')

    def __str__(self):
        return f"{self.last_try}"

    class Meta:
        verbose_name = 'Лог'
        verbose_name_plural = 'Логи'

mailing/forms.py
from django import forms

from catalog.forms import StyleFormMixin
from mailing.models import MailingSettings, Customer, Message


class MailingSettingsForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = MailingSettings
        fields = ('start_time', 'end_time', 'period', 'status', 'message')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['start_time'].widget.attrs['placeholder'] = 'YYYY-MM-DD HH:MM:SS'
        self.fields['end_time'].widget.attrs['placeholder'] = 'YYYY-MM-DD HH:MM:SS'
class CustomerForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Customer
        fields = ('email', 'first_name', 'last_name', 'comment')


class MessageForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Message
        fields = ('subject', 'body')


class MailingSettingsForManagerForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = MailingSettings
        fields = ('status',)

mailing/views.py
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import Http404
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, DeleteView, ListView, TemplateView

from mailing.forms import MailingSettingsForm, CustomerForm, MessageForm, MailingSettingsForManagerForm
from mailing.models import Customer, MailingSettings, MailingClient, Message
from mailing_blog.models import MailingBlog


class MailingSettingsListView(LoginRequiredMixin, ListView):
    model = MailingSettings

    def get_queryset(self):
        """Пользователь видит только свои рассылки"""
        queryset = super().get_queryset()
        if self.request.user.has_perm('mailing.view_mailingsettings'):
            return queryset  # Если есть право доступа, то пользователь видит все рассылки
        return queryset.filter(owner=self.request.user)


class MailingSettingsCreateView(LoginRequiredMixin, CreateView):
    model = MailingSettings
    form_class = MailingSettingsForm
    success_url = reverse_lazy('mailing:mailing_list')

    def form_valid(self, form):
        """ У рассылки появляется 'owner' - авторизированный пользователь """
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)


class MailingSettingsUpdateView(UserPassesTestMixin, UpdateView):
    model = MailingSettings
    form_class = MailingSettingsForm
    success_url = reverse_lazy('mailing:mailing_list')
    permission_required = 'mailing.change_mailingsettings'

    def test_func(self):
        mailing = self.get_object()
        user = self.request.user
        if mailing.owner == user or user.is_superuser:
            self.form_class = MailingSettingsForm
        elif user.has_perm('mailing.set_status'):
            self.form_class = MailingSettingsForManagerForm
        return user.is_authenticated and (mailing.owner == user or user.has_perm('mailing.set_status'))


class MailingSettingsDeleteView(LoginRequiredMixin, DeleteView):
    model = MailingSettings
    success_url = reverse_lazy('mailing:mailing_list')

    def get_object(self, queryset=None):
        """ Проверка на то, что пользователь не может удалять чужую рассылку """
        self.object = super().get_object(queryset)
        if self.object.owner != self.request.user:
            raise Http404
        return self.object


class MailingClientsListView(LoginRequiredMixin, ListView):
    """Клиенты рассылки"""

    model = MailingClient

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(settings=self.kwargs.get('pk'))
        return queryset

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        context_data['clients'] = Customer.objects.filter(owner=self.request.user)
        context_data['mailing_pk'] = self.kwargs.get('pk')

        return context_data


# customer

class CustomerListView(LoginRequiredMixin, ListView):
    model = Customer

    def get_queryset(self):
        """Пользователь видит только своих клиентов"""
        queryset = super().get_queryset()
        if self.request.user.has_perm('mailing.view_customer'):
            return queryset  # Если есть право доступа, то пользователь видит всех клиентов (у манагера нет)
        return queryset.filter(owner=self.request.user)


class CustomerCreateView(LoginRequiredMixin, CreateView):
    model = Customer
    form_class = CustomerForm
    success_url = reverse_lazy('mailing:customers')

    def form_valid(self, form):
        """ У клиента появляется 'owner' - авторизированный пользователь """
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)


class CustomerUpdateView(LoginRequiredMixin, UpdateView):
    model = Customer
    form_class = CustomerForm
    success_url = reverse_lazy('mailing:customers')

    def get_object(self, queryset=None):
        """ Проверка на то, что пользователь не может менять чужого клиента """
        self.object = super().get_object(queryset)
        if self.object.owner != self.request.user:
            raise Http404
        return self.object


class CustomerDeleteView(LoginRequiredMixin, DeleteView):
    model = Customer
    success_url = reverse_lazy('mailing:customers')

    def get_object(self, queryset=None):
        """ Проверка на то, что пользователь не может удалить чужого клиента """
        self.object = super().get_object(queryset)
        if self.object.owner != self.request.user:
            raise Http404
        return self.object


# message

class MessageListView(LoginRequiredMixin, ListView):
    model = Message

    def get_queryset(self):
        """Пользователь видит только свои сообщения"""
        queryset = super().get_queryset()
        if self.request.user.has_perm('mailing.view_message'):
            return queryset  # Если есть право доступа, то пользователь видит все сообщения
        return super().get_queryset().filter(owner=self.request.user)


class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('mailing:messages')

    def form_valid(self, form):
        """ У сообщения появляется 'owner' - авторизированный пользователь """
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('mailing:messages')

    def get_object(self, queryset=None):
        """ Проверка на то, что пользователь не может менять чужое сообщение """
        self.object = super().get_object(queryset)
        if self.object.owner != self.request.user:
            raise Http404
        return self.object


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    model = Message
    success_url = reverse_lazy('mailing:messages')

    def get_object(self, queryset=None):
        """ Проверка на то, что пользователь не может удалять чужое сообщение """
        self.object = super().get_object(queryset)
        if self.object.owner != self.request.user:
            raise Http404
        return self.object


def toggle_customer(request, pk, customer_pk):
    # удаление клиента из рассылки
    if MailingClient.objects.filter(client_id=customer_pk, settings_id=pk).exists():
        MailingClient.objects.filter(client_id=customer_pk, settings_id=pk).delete()
    # добавление в рассылку
    else:
        MailingClient.objects.create(client_id=customer_pk, settings_id=pk)

    return redirect(reverse('mailing:mailing_clients', args=[pk]))


class HomePageView(TemplateView):
    template_name = 'mailing/home.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['count_mailing'] = MailingSettings.objects.all().count()
        context_data['count_mailing_active'] = MailingSettings.objects.filter(
            status=MailingSettings.STATUS_STARTED).count()
        context_data['count_unique_customers'] = Customer.objects.distinct().count()
        context_data['mailing_blog'] = MailingBlog.objects.all()[:3]
        context_data['title'] = 'Главная страница рассылок'
        return context_data

mailing/templates/mailing/customer_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p> Хотите удалить покупателя "{{ object.email }}"? </p>
                        <button type="submit" class="btn btn-success">
                            Подтвердить
                        </button>
                        <a href="{% url 'mailing:customers' %}" class="btn btn-warning"> Отмена </a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/customer_form.html
{% extends 'catalog/base.html' %}
{% block content %}

<div class="col-12">
    <form method="post" enctype="multipart/form-data">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Покупатель</h3>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                            Сохранить
                            {% else %}
                            Создать
                            {% endif %}
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

mailing/templates/mailing/customer_list.html
{% extends "catalog/base.html" %}
{% block title %} Customers {% endblock title %}
{% block content %}
{% include 'mailing/includes/inc_buttons.html' %}

<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'mailing:customer_create' %}"> Добавить покупателя </a>
</div>


<div style="margin-left:50px" class="row mb-5">
    {% for object in object_list %}
    <div class="col-5">
        <div class="card">
            <div class="card-header">
                {{ object.first_name }} {{ object.last_name }}
            </div>
            <div class="card-body">
                {{ object.email }}
            </div>
            <div class="col-7">
                <div class="row">
                    <div class="col-6">
                        <a href="{% url 'mailing:customer_update' object.pk %}"
                           class="btn btn-outline-secondary">Изменить</a>
                    </div>
                    <div class="col-6">
                        <a href="{% url 'mailing:customer_delete' object.pk %}" class="btn btn-outline-secondary">Удалить</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock content %}

mailing/templates/mailing/home.html
{% extends "catalog/base.html" %}
{% block title %} Home {% endblock title %}
{% block content %}
{% include 'mailing/includes/inc_buttons.html' %}
<div class="col-12">
    <div class="card mb-5">
        <div class="card-header bg-dark text-white">
            <h1>Cервис рассылок</h1>
        </div>
        <div class="card-body">
            <p>Всего рассылок : {{ count_mailing }}</p>
            <p>Активных рассылок всего : {{ count_mailing_active }}</p>
            <p>Количество уникальных клиентов для рассылок : {{ count_unique_customers }}</p>
        </div>
    </div>
</div>
<div class="row mt-3">
    {% for object in mailing_blog %}
    <div class="col-4">
        <div class="card">
            <div class="card-body">
                <div class="card-header bg-dark text-white">
                    <h5> {{ object.title }}</h5>
                </div>

                <p>{{ object.content|truncatechars:100 }}</p>
                <!--                <div class="row">-->
                <!--                    <div class="col-3">-->
                <!--                        <a href="#" class="btn btn-outline-secondary">View</a>-->
                <!--                    </div>-->
                <!--                </div>-->
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock content %}

mailing/templates/mailing/mailingclient_list.html
{% extends "catalog/base.html" %}
{% block title %} Mailing clients {% endblock title %}
{% block content %}

<div class="row">
    <div class="col-6">
        <div class="col-12 mb-5">
            <p align="center"> Клиенты рассылки</p>
        </div>
        {% for object in object_list %}
        <div class="card">
            <div class="card-header">
                {{ object.client.first_name }}
                {{ object.client.last_name }}
            </div>
            <div class="card-body">
                {{ object.client.email}}
            </div>
            <div class="card-footer">
                <a href="{% url 'mailing:mailing_clients_toggle' mailing_pk object.client.pk %}"
                       class="btn btn-outline-secondary">Удалить</a>
            </div>
        </div>
        {% endfor %}
    </div>


    <div class="col-6">
        <div class="col-12 mb-5">
            <p align="center"> Клиенты для добавления </p>
        </div>
        <table class="table">
            <tr>
                <th>Имя</th>
                <th>Фамилия</th>
                <th>Email</th>
                <th>Добавить</th>
            </tr>
            {% for client in clients %}
            <tr>
                <td>{{ client.first_name }}</td>
                <td>{{ client.last_name }}</td>
                <td>{{ client.email }}</td>
                <td><a href="{% url 'mailing:mailing_clients_toggle' mailing_pk client.pk %}"
                       class="btn btn-outline-secondary">Добавить</a></td>
            </tr>
            {% endfor %}
        </table>
    </div>
</div>

{% endblock %}

mailing/templates/mailing/mailingsettings_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p> Хотите удалить рассылку "{{ object }}"? </p>
                        <button type="submit" class="btn btn-success">
                            Подтвердить
                        </button>
                        <a href="{% url 'mailing:mailing_list' %}" class="btn btn-warning"> Отмена </a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/mailingsettings_form.html
{% extends 'catalog/base.html' %}
{% block content %}

<div class="col-12">
    <form method="post">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Настройки рассылки</h3>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                            Сохранить
                            {% else %}
                            Создать
                            {% endif %}
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

mailing/templates/mailing/mailingsettings_list.html
{% extends 'catalog/base.html' %}
{% block content %}
{% include 'mailing/includes/inc_buttons.html' %}
<div class="row">
    <div class="col-12 mb-5">
        <a href="{% url 'mailing:mailing_create' %}" class="btn btn-success float-end">
            Создать рассылку
        </a>
    </div>
    <div class="col-12">
        <div class="row mb-5">
            {% for item in object_list %}
            <div class="col-6 mb-5">
                <div class="card">
                    <div class="card-header"> Рассылка #{{ item.pk }}</div>
                    <div class="card-body">
                        <table class="table">
                            <tr>
                                <td>Время начала</td>
                                <td>{{ item.start_time|date:"d-m-Y H:i" }}</td>
                            </tr>
                            <tr>
                                <td>Время окончания</td>
                                <td>{{ item.end_time|date:"d-m-Y H:i" }}</td>
                            </tr>
                            <tr>
                                <td>Период</td>
                                <td>{{ item.get_period_display }}</td>
                            </tr>
                            <tr>
                                <td>Статус</td>
                                <td>{{ item.get_status_display }}</td>
                            </tr>
                            <tr>
                                <td>Сообщение</td>
                                <td>{{ item.message }}</td>
                            </tr>
                        </table>
                    </div>
                    <div class="card-footer">
                        <a href="{% url 'mailing:mailing_clients' item.pk %}" class="btn btn-outline-secondary">Клиенты
                            рассылки</a>
                        <p></p>

                        <div class="row">
                            <div class="col-6">
                                <a href="{% url 'mailing:mailing_update' item.pk %}"
                                   class="btn btn-outline-secondary">Изменить</a>
                            </div>
                            <div class="col-6">
                                <a href="{% url 'mailing:mailing_delete' item.pk %}"
                                   class="btn btn-outline-secondary">Удалить </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/message_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p> Хотите удалить сообщение "{{ object }}"? </p>
                        <button type="submit" class="btn btn-success">
                            Подтвердить
                        </button>
                        <a href="{% url 'mailing:messages' %}" class="btn btn-warning"> Отмена </a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/message_form.html
{% extends 'catalog/base.html' %}
{% block content %}

<div class="col-12">
    <form method="post" enctype="multipart/form-data">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Сообщение</h3>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                            Сохранить
                            {% else %}
                            Создать
                            {% endif %}
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

mailing/templates/mailing/message_list.html
{% extends "catalog/base.html" %}
{% block title %} Message {% endblock title %}
{% block content %}
{% include 'mailing/includes/inc_buttons.html' %}

<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'mailing:message_create' %}"> Добавить сообщение </a>
</div>


<div style="margin-left:50px" class="row mb-5">
    {% for object in object_list %}
    <div class="col-5">
        <div class="card">
            <div class="card-header">
                {{ object.subject }}
            </div>
            <div class="card-body">
                {{ object.body }}
            </div>
            <div class="col-7">
                <div class="row">
                    <div class="col-6">
                        <a href="{% url 'mailing:message_update' object.pk %}"
                           class="btn btn-outline-secondary">Изменить</a>
                    </div>
                    <div class="col-6">
                        <a href="{% url 'mailing:message_delete' object.pk %}"
                           class="btn btn-outline-secondary">Удалить</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock content %}