catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page, never_cache

from catalog.views import ProductListView, ContactView, ProductDetailView, ProductUpdateView, BlogCreateView, \
    BlogUpdateView, BlogDetailView, BlogListView, BlogDeleteView, ProductDeleteView, ProductCreateView, \
    CategoryListView, CategoryProductListView

urlpatterns = [
    path('', ProductListView.as_view(), name='product_list'),
    path('contacts/', ContactView.as_view(), name='contacts'),
    path('create_product', never_cache(ProductCreateView.as_view()), name='product_create'),
    path('product/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='product_view'),
    path('edit/<int:pk>/', never_cache(ProductUpdateView.as_view()), name='product_edit'),
    path('delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),
    path('category/', CategoryListView.as_view(), name='category_list'),
    path('<int:pk>/products/', CategoryProductListView.as_view(), name='category_products'),

    path('create_blog/', never_cache(BlogCreateView.as_view()), name='create_blog'),
    path('edit_blog/<slug:slug>/', never_cache(BlogUpdateView.as_view()), name='edit_blog'),
    path('view_blog/<slug:slug>/', BlogDetailView.as_view(), name='view_blog'),
    path('list_blog/', BlogListView.as_view(), name='list_blog'),
    path('delete_blog/<slug:slug>/', BlogDeleteView.as_view(), name='delete_blog')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),
    path('users/', include('users.urls')),
    path('mailing/', include('mailing.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, ActivateView, CustomPasswordResetView, \
    CustomPasswordResetDoneView, CustomPasswordResetConfirmView, CustomPasswordResetCompleteView, UserUpdateView, \
    generate_new_password

app_name = UsersConfig.name
urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('register/', RegisterView.as_view(), name='register'),
    path('activate/<uidb64>/<token>', ActivateView.as_view(), name='activate'),

    path('reset_password/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('reset_password_sent/', CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset_password_complete/', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('genpassword/', generate_new_password, name='generate_new_password'),


    path('profile/', UserUpdateView.as_view(), name='profile')
]

catalog/models.py
from django.db import models

from config import settings

NULLABLE = {'blank': True, 'null': True}


class Product(models.Model):
    name = models.CharField(max_length=250, verbose_name='Название продукта')
    description = models.TextField(verbose_name='Описание')
    preview = models.ImageField(upload_to='products/', verbose_name='Изображение', **NULLABLE)
    category = models.ForeignKey('Category', on_delete=models.CASCADE, verbose_name='Категория')
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name='Цена', **NULLABLE)
    date_of_creation = models.DateTimeField(auto_now=True, auto_now_add=False, verbose_name='Дата создания')
    last_modified_date = models.DateTimeField(auto_now=True, auto_now_add=False,
                                              verbose_name='Дата последнего изменения')
    vendor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE, verbose_name='Продавец')
    def __str__(self):
        return f'{self.name} - {self.price}'

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'


class Category(models.Model):
    category = models.CharField(max_length=100, verbose_name='Категории')
    description = models.TextField(verbose_name='Описание')

    def __str__(self):
        return f'{self.category}'

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Продукт')
    version_number = models.PositiveIntegerField(verbose_name='Номер версии')
    name = models.CharField(max_length=150, verbose_name='Название версии')
    is_actual = models.BooleanField(verbose_name='Признак текущей версии')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Версия'
        verbose_name_plural = 'Версии'


class Blog(models.Model):
    title = models.CharField(max_length=100, verbose_name='Заголовок')
    slug = models.CharField(max_length=150, verbose_name='Slug')
    content = models.TextField(verbose_name='Содержимое')
    image = models.ImageField(upload_to='blog_preview/', **NULLABLE, verbose_name='Превью (изображение)')
    created_date = models.DateField(auto_now_add=True, verbose_name='Дата создания')
    is_published = models.BooleanField(default=True, verbose_name='Признак публикации')
    views_count = models.PositiveIntegerField(default=0, editable=False, verbose_name='Количество просмотров')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Запись'
        verbose_name_plural = 'Записи'

catalog/forms.py
from django import forms

from catalog.models import Product, Version


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name != 'is_actual':
                field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, forms.ModelForm):
    forbidden_words = ('казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар')
    class Meta:
        model = Product
        fields = ('name', 'description', 'category', 'preview', 'price')

    def clean_name(self):
        cleaned_data = self.cleaned_data['name']

        if any(word in cleaned_data.lower() for word in self.forbidden_words):
            raise forms.ValidationError('Запрещенное слово в названии')
        return cleaned_data

    def clean_description(self):
        cleaned_data = self.cleaned_data['description']
        if any(word in cleaned_data.lower() for word in self.forbidden_words):
            raise forms.ValidationError('Запрещенное слово в описании')
        return cleaned_data


class VersionForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'

catalog/views.py
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.cache import cache
from django.forms import inlineformset_factory
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, TemplateView, DetailView, UpdateView, CreateView, DeleteView
from pytils.translit import slugify

from catalog.forms import ProductForm, VersionForm
from catalog.models import Product, Blog, Version, Category
from catalog.services import get_cache_categories


class CategoryListView(ListView):
    model = Category
    queryset = get_cache_categories()


class CategoryProductListView(ListView):
    model = Product
    template_name = 'catalog/product_list.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(category_id=self.kwargs.get('pk'))
        return queryset

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)

        category_item = Category.objects.get(pk=self.kwargs.get('pk'))
        context_data['category_pk'] = category_item.pk
        context_data['title'] = f'{category_item.category}'
        return context_data


class ProductListView(ListView):
    model = Product
    extra_context = {
        'title': 'Главная'
    }


class ProductDetailView(DetailView):
    model = Product


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('product_list')
    login_url = 'users:login'

    def form_valid(self, form):
        self.object = form.save()
        self.object.vendor = self.request.user
        self.object.save()
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    login_url = 'users:login'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(self.model, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('product_view', args=[self.kwargs.get('pk')])


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('product_list')
    login_url = 'users:login'


class BlogCreateView(CreateView):
    model = Blog
    fields = ('title', 'content', 'image',)
    success_url = reverse_lazy('list_blog')  # куда редиректит - здесь переход к списку созданных

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ('title', 'content', 'image', 'is_published')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('view_blog', args=[self.kwargs.get('slug')])


class BlogListView(ListView):
    model = Blog
    extra_context = {
        'title': 'Блог'
    }

    def get_queryset(self, *args, **kwargs):
        """Выводить только те, у которых положительный признак публикации"""
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        """  Увеличивает количество просмотров """

        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save(update_fields=['views_count'])
        return self.object


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('list_blog')


class ContactView(TemplateView):
    template_name = 'catalog/contacts.html'
    extra_context = {
        'title': 'Контакты'
    }

    def post(self, request, **kwargs):
        context = self.get_context_data(**kwargs)
        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        if self.request.method == 'POST':
            name = self.request.POST.get('name')
            email = self.request.POST.get('email')
            message = self.request.POST.get('message')
            print(f'You have new message from {name} ({email}): {message}')
        return super().get_context_data(**kwargs)

# def contacts(request):
#     context = {
#         'title': 'Контакты'
#     }
#     if request.method == 'POST':
#         name = request.POST.get('name')
#         email = request.POST.get('email')
#         message = request.POST.get('message')
#         print(f'You have new message from {name} ({email}): {message}')
#     return render(request, 'catalog/contacts.html', context)

catalog/templates/catalog/base.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <style>
   .round {
   width: 40px; height: 40px;
   border-radius: 50%;
   }
   .butn {
   color:#fff;
   text-decoration:none;
   padding: 10px 15px;
   border-radius: 5px;

   }









    </style>
    <title>{% block title %} Title {% endblock title %}</title>
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-3">
            <div class="card bg-dark">
                <div class="card-body text-white">
                    {% include 'catalog/includes/inc_catalog_menu.html' %}
                    <div style="margin-top:350px" class="row">
                        {% if user.is_authenticated %}
                        <div class="col-3">
                            <img
                                    src="https://gamerwall.pro/uploads/posts/2022-09/1662447336_1-gamerwall-pro-p-koshka-s-grustnimi-glazami-krasivo-1.jpg"
                                    class="round"></div>
                        <div class="col-9">
                            <a href="{% url 'users:profile' %}" class="butn btn-outline-dark mt-5"> Профиль: {{user.first_name}} </a>
                            <p></p>
                            <a href="{% url 'users:logout' %}" class="butn btn-outline-dark mt-5"> Выход </a>
                        </div>
                        {% else %}
                        <a href="{% url 'users:login' %}" class="butn btn-outline-dark mt-5"> Вход </a>
                        <a href="{% url 'users:register' %}" class="butn btn-outline-dark mt-5"> Регистрация </a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="row mt-5">
                <h3 align="center">{{ title }}</h3>
                {% block content %}{% endblock content %}
            </div>
        </div>
    </div>
</div>
</body>
</html>

catalog/templates/catalog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p> Хотите удалить запись "{{ object.title }}"? </p>
                        <button type="submit" class="btn btn-success">
                            Подтвердить
                        </button>
                        <a href="{% url 'list_blog' %}" class="btn btn-warning"> Отмена </a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/blog_detail.html
{% extends 'catalog/base.html' %}
{% load tags_filters %}
{% block content %}
<div class="col-12">
    <div class="row">

        <div class="col-6">
            <div class="card">
                {% if object.image %}
                <img src="{{ object.image|mediapath}}" class="card-img-top">
                {% endif %}
                <div class="card-header">
                    <h3 class="card-title"> {{object.title}} </h3>
                </div>
                <div class="card-body">
                    <p>
                        {{ object.content}}
                    </p>
                    <div class="col-6">
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a href="{% url 'edit_blog' object.slug %}"
                                   class="btn btn-sm btn-outline-secondary">Edit</a>
                                <a href="{% url 'delete_blog' object.slug %}"
                                   class="btn btn-sm btn-outline-danger">Delete</a>
                            </div>
                        </div>
                    </div>

                </div>
                <div class="card-footer">
                    Просмотры: {{ object.views_count }}
                    <p></p>
                    {{ object.created_date }}
                </div>

            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/blog_form.html
{% extends 'catalog/base.html' %}
{% block content %}

<div class="col-12">
    <div class="row">
        <div class="col-9">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                            Сохранить
                            {% else %}
                            Создать
                            {% endif %}

                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/blog_list.html
{% extends "catalog/base.html" %}
{% block title %} Blog {% endblock title %}
{% block content %}
{% load tags_filters %}

<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'create_blog' %}">Добавить блоговую запись</a>
</div>


<div style="margin-left:50px" class="row mt-3">
    {% for object in object_list %}
    <div class="col-5">
        <div class="card">
            <div class="card-body">
                <h5><p class="card-title"> {{ object.title }} </p></h5>

                <p>{{ object.content|truncatechars:100 }}</p>
                <div class="row">
                    <div class="col-3">
                        <a href="{% url 'view_blog' object.slug %}" class="btn btn-outline-secondary">View</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock content %}

catalog/templates/catalog/category_list.html
{% extends "catalog/base.html" %}
{% block title %} Categories {% endblock title %}
{% block content %}


<h3 align="center"> Категории товаров </h3>


<div style="margin-left:50px" class="row mb-5">
    {% for object in object_list %}
    <div class="col-5">
        <div class="card" style="height: 220px">
            <div class="card-body">

                <h5> {{ object.category }} </h5>
                <p>{{ object.description|truncatechars:100 }}</p>
            </div>
            <div class="card-footer">
                <div class="col-3">
                    <a href="{% url 'category_products' object.pk %}" class="btn btn-outline-secondary">Товары</a>
                </div>
            </div>

        </div>
    </div>
    {% endfor %}
</div>
{% endblock content %}

catalog/templates/catalog/contacts.html
{% extends "catalog/base.html" %}
{% block title %} Contacts {% endblock title %}
{% block content %}


        <div class="row mt-5">
            <div class="col-5">
                <form method="post">
                    {% csrf_token %}
                    <p>Имя</p>
                    <input type="text" name="name" class="form-control">
                    <p style="margin-top:20px">Почта</p>
                    <div class="input-group">
                        <span class="input-group-text" id="basic-addon1">@</span>
                        <input type="email" name="email" class="form-control" id="exampleInputEmail"
                               aria-describedby="emailHelp">
                    </div>
                    <p style="margin-top:20px">Сообщение</p>
                    <textarea name="message" class="form-control" id="exampleFormControlTextarea"
                              rows="3"></textarea>
                    <div class="col-6 mt-3">
                        <input type="submit" class="btn btn-primary form-control" value="Отправить"/>
                    </div>

                </form>
            </div>
            <div style="margin-left:70px" class="col-5 ">
                <h4>Наши контакты</h4>
                <p>Здесь находится текст с информацией о наших контактных данных, через которые вы можете с нами
                    связаться</p>
                <p>Have a nice day! :)</p>

            </div>
        </div>
    </div>
</div>
{% endblock content %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p> Хотите удалить товар "{{ object.name }}"? </p>
                        <button type="submit" class="btn btn-success">
                            Подтвердить
                        </button>
                        <a href="{% url 'list_blog' %}" class="btn btn-warning"> Отмена </a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends "catalog/base.html" %}
{% block title %} Products {% endblock title %}
{% block content %}
{% load tags_filters %}

<div class="col-7">
    <div class="card">
        <div class="card-body">
            {% if object.preview %}
                <img src="{{ object.preview|mediapath}}" class="card-img-top">
                {% else %}
                <img src="/media/skoro-foto-650x650.jpg" class="card-img-top">
                {%endif%}
            <h5><p class="card-title"> {{ object.name }} </p></h5>
            <h6><p class="card-text">Цена: {{ object.price }} руб</p></h6>
            <p>{{ object.category }}</p>
            <p>{{ object.description }}</p>
            {% if object.vendor %}
            <p>{{ object.vendor }}</p>
            {% endif %}
            <div class="row">
                {% if user.is_authenticated %}
                <div class="col-7">
                    <div class="btn-group" role="group" aria-label="Basic outlined example">
                        <a href="{% url 'product_edit' object.pk %}" class="btn btn-outline-secondary">Edit</a>
                        <a href="{% url 'product_delete' object.pk %}" class="btn btn-outline-secondary">Delete</a>
                    </div>
                </div>
                {% endif %}
                <div class="col text-secondary">
                    <p> {{ object.last_modified_date }} </p>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock content %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}
{% block content %}

<div class="col-12">
    <form method="post" enctype="multipart/form-data">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Товар</h3>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                            Сохранить
                            {% else %}
                            Создать
                            {% endif %}

                        </button>

                    </div>
                </div>
            </div>
            {% if object %}
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Версия</h3>
                    </div>
                    <div class="card-body">
                        {{ formset.management_form }}
                        {% for form in formset.forms %}
                        {{ form.as_p }}
                        {% if not forloop.last %}
                        <hr>
                        {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>
            {% endif %}
        </div>
    </form>
</div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends "catalog/base.html" %}
{% block title %} Homepage {% endblock title %}
{% block content %}
{% load tags_filters %}

<p class="text-muted" align="center">Вы находитесь на сайте, предназначенном для продажи товаров
</p>

{% if user.is_authenticated %}
<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'product_create' %}"> Добавить товар </a>
</div>
{% endif %}

<div style="margin-left:50px" class="row mb-5">
    {% for object in object_list %}
    <div class="col-5">
        <div class="card">
            <div class="card-body">
                {% if object.preview %}
                <img src="{{ object.preview|mediapath}}" class="card-img-top">
                {% else %}
                <img src="/media/skoro-foto-650x650.jpg" class="card-img-top">
                {%endif%}

                <h5><p class="card-title"> {{ object.name }} </p></h5>
                <h6><p class="card-text">Цена: {{ object.price }} руб</p></h6>
                <p>{{ object.description|truncatechars:100 }}</p>
                <div class="row">
                    <div class="col-3">
                        <a href="{% url 'product_view' object.pk %}" class="btn btn-outline-secondary">View</a>
                    </div>
                </div>

                {% for version_item in object.version_set.all %}
                {% if version_item.is_actual %}
                <div class="card-footer">
                    <p>Актуальная версия: {{ version_item.name }} - номер {{ version_item.version_number }} </p>
                </div>
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock content %}